### PR TITLE
fix(core): various improvements

### LINKED ISSUE #12: Various issues that prevented us from using this resource
Hello!

Thanks for making this OCI Helm Chart resource available as open source.

My team at DNAstack put this resource to use recently, and there were a number of small modifications/improvements we had to make in order for it to meet our needs:

* We were getting TLS certificate validation errors connecting to the Google Artifact Registry, so we added a ca-certificates update to the Dockerfile
* The check step was returning errors, but we couldn't tell which registry request those errors were coming from, so we added context info wrapping each call to the oras library.
* We have some images with abbreviated version strings like `1.0-foo` which lack the semver patch field, leading to 404 errors when trying to resolve the normalized version of the tag, eg. `1.0.0-foo`, so we changed the code to ensure the original tag string is used for everything except sorting and comparing versions.
* We ran into configuration errors where `check` succeeded but `in` failed because the example in README.md shows the repo name in the wrong config field, so we corrected the example in the README.
* Finally, we needed to pin our helm chart to a non-current version, so we changed the `check` step to provide the 10 latest versions on the initial check. As a side effect, we also improved the `check` logic so it returns all versions newer than the previous latest version, so there are no gaps in the list of versions available through the resource.

All the above changes are on [this branch](https://github.com/DNAstack/concourse-oci-helm-chart-resource/tree/various-fixes) in our fork of the repo. Would you be open to having us contribute them back to this project?

### PR DESCRIPTION
**Pull request by jfuerth**
This is a handful of changes my team made to this resource in order to get things working for us. We think these changes will benefit others in the community.

See issue #12 for details.

### CODE REVIEW

File: pkg/resource/check.go [hunk 1]
```diff
@@ -6,10 +6,11 @@ package resource
 import (
 	"context"
 	"fmt"
```
Comment (SuperSandro2000) [inline pkg/resource/check.go:8]:
```suggestion
	"fmt"
	"slices"

```

I think we are missing the goimports linter in this repo but lets make it nice for when we add it.

File: pkg/resource/check.go [hunk 2]
```diff
@@ -6,10 +6,11 @@ package resource
...
-
 	"github.com/Masterminds/semver/v3"
 	"github.com/pkg/errors"
 	"oras.land/oras-go/v2/registry"
+	"oras.land/oras-go/v2/registry/remote"
+	"slices"
```
Comment (SuperSandro2000) [inline pkg/resource/check.go:13]:
```suggestion
```

File: pkg/resource/check.go
Comment (SuperSandro2000) [inline pkg/resource/check.go:1]: I didn't look at this file in detail. Everything else LGTM

**Comment by jfuerth** [comment]
> @jfuerth can you please rebase your pr based on master ? We did some changes to bring the repo up to speed.

@kengou done!

I was busy with another project last week and it took longer than I would have liked to come back and rebase this on top of your changes.

Note also: I've just tacked on one more small change based on our real-world experience using the resource: in check.go, we're now ignoring tags that aren't semver rather than failing the whole check on them. This arose because we were getting resource checking errors from a repo where someone had added a "deployed-in-prod" tag.

**Comment by abhijith-darshan** [comment]
> @kengou @SuperSandro2000 just bumping this for your attention. The only failing check seems to be failing due to an image pull error. Maybe transient, but I don't have a retry button with my permissions.

When workflows involve secret and a PR is made from a fork by integration design it would fail this is expected.

@kengou maybe we can look into permissions for the `action-semantic-pull-request` action if possible.

File: pkg/resource/check.go [hunk 3]
```diff
@@ -28,33 +31,76 @@ func (cr *CheckRequest) Validate() error {
...
+	var j = 0
+	for _, tag := range allTags {
+		v, err := semver.NewVersion(tag)
+		if err != nil {
+			fmt.Fprintf(os.Stderr, "skipping tag %q because it does not look like a semver\n", tag)
+		} else {
+			allVersions[j] = *v
+			j++
+		}
+	}
```
Comment (kengou) [inline pkg/resource/check.go:89]: You can simplify the code by removing the `else` block and using `continue`

```suggestion
	for _, tag := range allTags {
		v, err := semver.NewVersion(tag)
		if err != nil {
			fmt.Fprintf(os.Stderr, "skipping tag %q because it does not look like a semver\n", tag)
			continue
		}
		allVersions[j] = *v
		j++
	}
```

**Review by kengou — COMMENTED** [review]
Looks good to me, only found one NIT. If you can take a look into that

**Comment by kengou** [comment]
> > @kengou @SuperSandro2000 just bumping this for your attention. The only failing check seems to be failing due to an image pull error. Maybe transient, but I don't have a retry button with my permissions.
> 
> When workflows involve secret and a PR is made from a fork by integration design it would fail this is expected.
> 
> @kengou maybe we can look into permissions for the `action-semantic-pull-request` action if possible.

Only the PR title check is failing, will take a look into that later, that should not hinder us from merging

**Comment by jfuerth** [comment]
> Looks good to me, only found one NIT. If you can take a look into that

Thanks for the suggestion. Applied!
